### ISSUE TITLE
log scraper down time

### ISSUE THREAD

**Issue by rickonz** [Urban-Research-Group/outage-data-scraper#12]
problem: scraper error due to network/server side issue, can we trace what period of time the issue happened?
method: when scrapers through error exception, log the output and timestamp for future analysis?

**Comment by rickonz** [comment]
per discussion with @Gting6 , currently retrospectively plot scraped data's timestamp over time then investigate long pause period in cloudwatch log. would be better if 
1. handle scraper error with error output easier for cloudwatch log query for specific state -> layout -> provider -> time
2. integrate with cloudwatch alarm

**Comment by Gting6** [comment]
Finished at commit e6b6e5640f596cbe8a371d9000385a4cc08c1125
In the future we will directly record scraper error and reason into S3 bucket `scraperdowntime`, no need to check the logs or timestamps of the data.
